title: Portfolio - José Boon
baseurl: "/joseboon-portfolio"

github_username:  josejboon
author: josejboon
email: josejboon@gmail.com

theme: jekyll-theme-slate
markdown: kramdown

sass:
  sass_dir: _sass